---
version: '3'
services:

  weather:
    image: registry.gitlab.com/webtechnologiesabkl/registry/weather:latest
    container_name: weather
    expose:
      - "8090"
    restart: always

  rasa:
    image: registry.gitlab.com/webtechnologiesabkl/registry/rasa:latest
    container_name: rasa
    expose:
      - "5005"
    restart: always

  backend:
    image: registry.gitlab.com/webtechnologiesabkl/registry/backend:latest
    container_name: backend
    ports:
      - "8085:8085"
    expose:
      - "8085"
    links:
      - weather:weather
      - rasa:rasa
    restart: always

  website:
    image: registry.gitlab.com/webtechnologiesabkl/registry/website:latest
    container_name: website
    ports:
      - "80:80"
    expose:
      - "80"
    restart: always
