---
version: '3'
services:

  weather:
    image: registry.gitlab.com/webtechnologiesabkl/registry/weather:latest
    container_name: weather
    expose:
      - "8090"
    restart: always

  duckling:
    image: registry.gitlab.com/webtechnologiesabkl/registry/duckling:latest
    container_name: duckling
    expose:
      - "8000"
    restart: always

  rasa:
    image: registry.gitlab.com/webtechnologiesabkl/registry/rasa:latest
    container_name: rasa
    ports:
      - "5005:5005"
    expose:
      - "5005"
    links:
      - duckling:duckling
    restart: always
    depends_on:
      - duckling

  backend:
    image: registry.gitlab.com/webtechnologiesabkl/registry/backend:latest
    container_name: backend
    ports:
      - "8085:8085"
    expose:
      - "8085"
    links:
      - weather:weather
      - rasa:rasa
    restart: always
    depends_on:
      - rasa
      - duckling
      - weather

  website:
    image: registry.gitlab.com/webtechnologiesabkl/registry/website:latest
    container_name: website
    ports:
      - "80:80"
    expose:
      - "80"
    restart: always
    depends_on:
      - rasa
      - duckling
      - weather
      - backend
