---
version: '3'
services:

  weather:
    image: registry.gitlab.com/webtechnologiesabkl/registry/weather:latest
    container_name: weather
    expose:
      - "8090"
    restart: always

  backend:
    image: registry.gitlab.com/webtechnologiesabkl/registry/backend:latest
    container_name: backend
    ports:
      - "8085:8085"
    expose:
      - "8085"
    links:
      - weather:weather
    restart: always

